version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/runtimes/cloudformation"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/pkg"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
