version: 1

before:
  hooks:
    - make -C runtimes/cloudformation clean agent-kilt.zip

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: zip
    name_template: "agent-kilt-{{ .Os }}-{{ .Arch }}"

release:
  extra_files:
    - glob: ./runtimes/cloudformation/kilt.zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
