version: 2

project_name: agent-kilt

builds:
  - id: image-info
    no_unique_dist_dir: true
    binary: image-info/image-info-{{ .Os }}-{{ .Arch }}
    main: ./cmd/cfn-image-info
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

  - id: apply-kilt
    no_unique_dist_dir: true
    binary: apply-kilt/apply-kilt-{{ .Os }}-{{ .Arch }}
    main: ./cmd/cfn-apply-kilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

snapshot:
  version_template: "{{ .Env.BUILD_VERSION }}"
