name: Quality Gate

on:
  pull_request:
    branches: [ dev ]

env:
  GO_VERSION: 1.20.x

jobs:
  test-pkg-lib:
    name: Test pkg lib
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: |
          cd pkg
          go test -v ./...

  test-cfn-runtime:
    name: Test CloudFormation Runtime
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: |
          cd runtimes/cloudformation
          go test -v ./...

  build-cfn-runtime:
    name: Build CloudFormation runtime
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build agent-kilt handler
        run: |
          make -C runtimes/cloudformation clean cmd/handler/handler
